spring:
  config:
    import:
      db.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create #update
    properties:
      hibernate:
        use-new-id-generator-mappings: false
       # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug